### ISSUE TITLE
Did you know your private keys are public?

### ISSUE THREAD

**Issue by rvdende** [sw00/dotfiles#1]
Hi Sett, hope its going well. Just randomly stumbled into your dotfiles and ssh folder.. listen its not a good idea to commit all your private keys to a public repo! All these keys need to be replaced and access revoked on the remote machines!

**Comment by sw00** [comment]
Hey! Thanks for your concern and the heads up - although this issue got buried somehow and I completely missed it. 

Rest assured, there's less risk than it seems. You'll be interested in the explanation:

- I use [git-crypt](https://www.agwa.name/projects/git-crypt), so my keys are never actually comitted to the repo in their plaintext form.

- In addition to the mangling that git-crypt does, each key is still protected with a unique passphrase (using the standard SSH passphrase mechanism, 128 bit AES)

- A lot of the keys are old, defunct and have already been revoked long ago - they just weren't removed from this repo.

### Why?

I set it up this way a long time ago when I was experimenting with "ephemeral workstations" - i.e. being able to work in any environment/machine as long as it had a posix terminal.

The idea behind an "ephemeral workstation" is this: all I'd need to work is my dotfiles and my password manager. So I can provision and continue my work within minutes, whether it's on a VPS or linux booted from USB.

Of course, a major downside to git-crypt, is that there's information leakage in terms of filenames.

But I've since moved on and only keep low-value keys in this repo now.

**Comment by sw00** [comment]
Keys will be purged, rotated as part of current cleanup.
